# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/node_modules
  CACHED_BUILD_PATHS: ${{ github.workspace }}/.next
  BUILD_CACHE_KEY: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Show NodeJS version    
      run: npm --version
    - name: Install Dependencies
      run: npm ci
    # - name: Install Truffle
    #   run: npm install truffle -g
    - name: Show Truffle version    
      run: npx truffle version
    # - name: Install Ganache
    #   run: npm install ganache -g
    - name: Show Ganache version    
      run: npx ganache --version
    - name: Start ganache
      run: |
        npx ganache -p 7545 > /dev/null &
    - name: Run Truffle Test with CI=true for Codechecks  
      run: CI=true npx truffle test
    # - name: Run Codechecks
    #   run: npx codechecks
    #   env:
    #     CC_SECRET: ${{ secrets.CC_SECRET }} 
    - name: Run Test Coverage
      run: npx truffle run coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        id: slither
        continue-on-error: true
        with:
          sarif: results.sarif
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
    - name: Stop ganache
      run: kill $(lsof -t -i:7545)
      
      
      
      
      
